### ISSUE TITLE
Code Review Checklist

### ISSUE THREAD

**Issue by jocelyn-boyd** [karyRmartinez/Artspace2.0#15]
### Pull Requests
- [ ] **Should be small and and frequently integrated.** [Feature toggles](https://martinfowler.com/articles/feature-toggles.html), sometimes called feature flags, can help with this. They're clever tools to enable larger chunks of work to be broken into a collection of incremental pull requests. 

### Readability a.k.a "Understandability"
- [ ] **Agree on a standard format and stick to it.** 
- [ ] **Ensure the proper naming conventions.** [Naming Conventions in Swift](https://medium.com/better-programming/naming-conventions-in-swift-4b7ca5eed4d2)
- [ ] **Edit any unreadable and not properly named code.** The method or class name should describe its work correctly.

### Documentation
- [ ] **Remove comment if they have no information.** Comment should explain why the code is written and if there are complicated business rules or workaround solutions. 

### Maitainability and Reliability 
- [ ] **Maintain MVC design pattern.** Any parts that do not fit the layered architecture should be corrected.
- [ ] **Fit the purpose.** Double-check that the code actually provides the functionality that the code actually provides the functionality is was meant to provide.
- [ ] **The code blocks should be concise.** Make sure that the code is separated into blocks and each block has it's own and only responsibility. (Single Responsibility Principle)
- [ ] **Code duplication should be checked - DRY.** (Don't Repeat Yourself) If there is code written for the same purpose in the project, that code should be used or changed so that it can be used.
- [ ] **Don't reinvent the wheel.** Make sure the code uses all the appropriate language features. 
- [ ] **Reliable code is written on the assumption that things will fail.** Assets will sometimes not load, API requests will occasionally return 500 errors and database records will be missing. When a certain level of failure is anticipated, it can be handled elegantly.
- [ ] **Be sure that exceptions and errors are handled and logged properly.** If the method returns an error code, check that if it describes the error properly.

### Test Coverage and Test Quality 
- [ ] **Think through whether there are tests that are missing.** Are there edge cases that haven't been tested? Test should readable, maintainable, performant and adhere to established patterns. 

### Resusability 
- [ ] Make sure that the code can easily be updated to support new kinds of features in the future. 

### Scalability 
- [ ] **Consider what is likely to happen to the code under periods of very high usage.** Imagine what might happen to the code if it were put under an unexpected load. What happens to your app when it is hit with dozens for requests per second? What happens if your product appears in the news and 100 try to buy it all at once?

### Security 
- [ ] **The code should be checked for security as possible as you can.**

### Speed and Performance 
- [ ] **Performance checks should be done.**
