### ISSUE TITLE
Authentication Screen Task List

### ISSUE THREAD

**Issue by jocelyn-boyd** [karyRmartinez/Artspace2.0#16]
## Login Screen
- [x] test Firebase methods 
- [x] add transition method to the main feed
- [x] user can login in successfully
- [x] user can sign out successfully

## Signup Screen
- [x] add validateUserCrendentaials computed property 
- [x] add showErrorAlert method 
- [x] add transitionToMainFeedVC method
- [x] add Firebase method -> handleCreateAccountResponse
- [x] add Firebase method -> signupUser
- [x] add objc method -> signupButtonPressed
- [x] user can login successfully

Extra -> Hardware: 
- [x] add createDismissKeyboardGesture method
- [x] add UITextFieldDelegate extension -> textFieldShouldReturn method

**Comment by jocelyn-boyd** [comment]
- <b>test login<b>
  - email: user@test.com
  - pw: password
